<?php

use App\Course;
use Illuminate\Database\Seeder;

class CourseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $domain = "BrainsterTools";
        $courses  = [
            [
                'course_url' => "https://click.linksynergy.com/deeplink?id=jU79Zysihs4&mid=39197&murl=https://www.udemy.com/after-effects-kinetic-typography?ref=http://localhost:9999",
                'course_name' => "After Effects CC 2019: Complete Course from Novice to Expert",
                'course_type' => 0,
                'course_price_type'=> 1,
                'course_language' => 0,
                'user_id' => 1, 
                'course_aproved' => 1, 
                'main_id' => 1,
                
            ],
            [
                'course_url' => "https://helpx.adobe.com/after-effects/tutorials.html?ref=hackr.io?ref=http://localhost:9999",
                'course_name' => "Create Incredible Motion Graphics and Visual Effects",
                'course_type' => 0,
                'course_price_type'=> 1,
                'course_language' => 0,
                'user_id' => 1, 
                'course_aproved' => 1, 
                'main_id' => 1,
                
            ],
            [
                'course_url' => "https://www.youtube.com/watch?v=8LtY7qWWyAY&ref=hackr.io",
                'course_name' => "How to Get Started with Adobe After Effects CC - 10 Things Beginners Want to Know How To Do",
                'course_type' => 0,
                'course_price_type'=> 0,
                'course_language' => 0,
                'user_id' => 1, 
                'course_aproved' => 1, 
                'main_id' => 1,
                
            ],
            [
                'course_url' => "https://www.youtube.com/playlist?list=PLOVqmUlWq2N_z2kn5n9hJq-H6jUUWsAWy&ref=hackr.io",
                'course_name' => "After Effects CC 2015 Tutorials for Beginners",
                'course_type' => 0,
                'course_price_type'=> 1,
                'course_language' => 0,
                'user_id' => 1, 
                'course_aproved' => 1, 
                'main_id' => 1,
            ],
            [
                'course_url' => "https://www.youtube.com/playlist?list=PLJ4RelYJHoScuihpL_8-Om6UZIkhuW_zm&ref=hackr.io",
                'course_name' => "Adobe Experience Design CC",
                'course_type' => 0,
                'course_price_type'=> 0,
                'course_language' => 0,
                'user_id' => 1, 
                'course_aproved' => 1, 
                'main_id' => 2,
            ],
            [
                'course_url' => "https://click.linksynergy.com/deeplink?ref=http://localhost:9999",
                'course_name' => "UI/UX design with Adobe XD: Design & Prototype a Mobile App",
                'course_type' => 0,
                'course_price_type'=> 0,
                'course_language' => 0,
                'user_id' => 1, 
                'course_aproved' => 1, 
                'main_id' => 2,
            ],
            [
                'course_url' => "https://webdesign.tutsplus.com/tutorials/how-to-use-responsive-resize-and-constraints-in-adobe-xd--cms-32019?ref=http://localhost:9999",
                'course_name' => "How to Use Responsive Resize and Constraints in Adobe XD",
                'course_type' => 0,
                'course_price_type'=> 0,
                'course_language' => 0,
                'user_id' => 1, 
                'course_aproved' => 1, 
                'main_id' => 2,
            ],
            [
                'course_url' => "https://www.youtube.com/watch?v=kCshcZ5mzPs&ref=hackr.io",
                'course_name' => "Premiere Pro CC 2017 - Full Tutorial for Beginners",
                'course_type' => 0,
                'course_price_type'=> 0,
                'course_language' => 0,
                'user_id' => 1, 
                'course_aproved' => 1, 
                'main_id' => 3,
            ],
            [
                'course_url' => "https://click.linksynergy.com/deeplink?ref=${domain}",
                'course_name' => "Adobe Premiere Pro CC: Learn Video Editing In Premiere Pro",
                'course_type' => 0,
                'course_price_type'=> 1,
                'course_language' => 0,
                'user_id' => 1, 
                'course_aproved' => 1, 
                'main_id' => 3,
            ],
            [
                'course_url' => "https://helpx.adobe.com/premiere-pro/tutorials.html?ref=${domain}",
                'course_name' => "Adobe Premiere Pro tutorials",
                'course_type' => 0,
                'course_price_type'=> 1,
                'course_language' => 0,
                'user_id' => 1, 
                'course_aproved' => 1, 
                'main_id' => 3,
            ],
            [
                'course_url' => "https://www.youtube.com/watch?v=kTno2oBN24E&t=8812s&ref=hackr.io",
                'course_name' => "CardView & RecyclerView Complete Course",
                'course_type' => 0,
                'course_price_type'=> 0,
                'course_language' => 0,
                'user_id' => 1, 
                'course_aproved' => 1, 
                'main_id' => 4,
            ],
            [
                'course_url' => "http://web.stanford.edu/class/cs193a/videos.shtml?ref=hackr.io",
                'course_name' => "Android App Development by Stanford",
                'course_type' => 0,
                'course_price_type'=> 0,
                'course_language' => 0,
                'user_id' => 1, 'course_aproved' => 1, 
                'main_id' => 4,
            ],
            [
                'course_url' => "https://www.udemy.com/course/complete-android-n-developer-course",
                'course_name' => "The Complete Android N Developer Course",
                'course_type' => 0,
                'course_price_type'=> 0,
                'course_language' => 0,
                'user_id' => 1, 'course_aproved' => 1, 
                'main_id' => 4,
            ],
            [
                'course_url' => "https://www.youtube.com/playlist",
                'course_name' => "Android Material Design Tutorial",
                'course_type' => 0,
                'course_price_type'=> 0,
                'course_language' => 0,
                'user_id' => 1, 'course_aproved' => 1, 
                'main_id' => 4,
            ],
            [
                'course_url' => "https://click.linksynergy.com/deeplink?id=jU79Zysihs4&mid=39197&murl=https://www.udemy.com/ultimate-photoshop-training-from-beginner-to-pro/",
                'course_name' => "Ultimate Photoshop Training: From Beginner to Pro",
                'course_type' => 0,
                'course_price_type'=> 0,
                'course_language' => 0,
                'user_id' => 1, 'course_aproved' => 1, 
                'main_id' => 5,
            ],
            [
                'course_url' => "https://www.youtube.com/watch?v=9z3N5Ti9sCo&ref=${domain}",
                'course_name' => "Photoshop CS6 For Beginners",
                'course_type' => 0,
                'course_price_type'=> 0,
                'course_language' => 0,
                'user_id' => 1, 'course_aproved' => 1, 
                'main_id' => 5,
            ],
            [
                'course_url' => "https://www.youtube.com/playlist?list=PLSoOtQkDh8ByH7x6eQfjVt09V9GJMxL2Z&ref=${domain}",
                'course_name' => "104 Photoshop Video Tutorials",
                'course_type' => 0,
                'course_price_type'=> 0,
                'course_language' => 0,
                'user_id' => 1, 'course_aproved' => 1, 
                'main_id' => 5,
            ],
            [
                'course_url' => "https://www.youtube.com/channel/UCMrvLMUITAImCHMOhX88PYQ/featured?ref=hackr.io",
                'course_name' => "PiXimperfect Photoshop Tutorials",
                'course_type' => 0,
                'course_price_type'=> 0,
                'course_language' => 0,
                'user_id' => 1, 'course_aproved' => 1, 
                'main_id' => 5,
            ],
            [
                'course_url' => "https://click.linksynergy.com/deeplink?id=jU79Zysihs4&mid=39197&murl=https://www.udemy.com/angular-2-and-nodejs-the-practical-guide/",
                'course_name' => "Angular & NodeJS - The MEAN Stack Guide",
                'course_type' => 0,
                'course_price_type'=> 0,
                'course_language' => 0,
                'user_id' => 1, 'course_aproved' => 1, 
                'main_id' => 6,
            ],
            [
                'course_url' => "https://www.udemy.com/course/the-complete-guide-to-angular-2/?LSNPUBID=jU79Zysihs4&ranEAID=jU79Zysihs4&ranMID=39197&ranSiteID=jU79Zysihs4-La3IccX3pCco51As.haAkw",
                'course_name' => "Angular 8 - The Complete Guide",
                'course_type' => 0,
                'course_price_type'=> 0,
                'course_language' => 0,
                'user_id' => 1, 'course_aproved' => 1, 
                'main_id' => 6,
            ],
            [
                'course_url' => "https://pluralsight.pxf.io/r1zJQ",
                'course_name' => "Shaping up with AngularJS",
                'course_type' => 0,
                'course_price_type'=> 1,
                'course_language' => 0,
                'user_id' => 1, 'course_aproved' => 1, 
                'main_id' => 6,
            ],
            [
                'course_url' => "https://click.linksynergy.com/deeplink?id=jU79Zysihs4&mid=39197&murl=https://www.udemy.com/the-complete-angular-master-class",
                'course_name' => "The Complete Angular Course: Beginner to Advanced",
                'course_type' => 0,
                'course_price_type'=> 1,
                'course_language' => 0,
                'user_id' => 1, 'course_aproved' => 1, 
                'main_id' => 6,
            ],
            [
                'course_url' => "https://click.linksynergy.com/deeplink?id=jU79Zysihs4&mid=39197&murl=https://www.udemy.com/the-complete-javascript-course/",
                'course_name' => "The Complete JavaScript Course 2019: Build Real Projects!",
                'course_type' => 0,
                'course_price_type'=> 0,
                'course_language' => 0,
                'user_id' => 1, 'course_aproved' => 1, 
                'main_id' => 7,
            ],
            [
                'course_url' => "http://eloquentjavascript.net/?ref=${domain}",
                'course_name' => "Eloquent JavaScript",
                'course_type' => 0,
                'course_price_type'=> 0,
                'course_language' => 0,
                'user_id' => 1, 'course_aproved' => 1, 
                'main_id' => 7,
            ],
            [
                'course_url' => "https://www.manning.com/books/secrets-of-the-javascript-ninja-second-edition?a_aid=hackrio",
                'course_name' => "Secrets of the JavaScript Ninja, Second Edition",
                'course_type' => 0,
                'course_price_type'=> 0,
                'course_language' => 0,
                'user_id' => 1, 'course_aproved' => 1, 
                'main_id' => 7,
            ],
            [
                'course_url' => "http://javascript.info/?ref=${domain}",
                'course_name' => "The JavaScript Tutorial",
                'course_type' => 0,
                'course_price_type'=> 0,
                'course_language' => 0,
                'user_id' => 1, 'course_aproved' => 1, 
                'main_id' => 7,
            ],
            [
                'course_url' => "https://click.linksynergy.com/deeplink?id=jU79Zysihs4&mid=39197&murl=https://www.udemy.com/php-for-complete-beginners-includes-msql-object-oriented/",
                'course_name' => "PHP for Beginners",
                'course_type' => 0,
                'course_price_type'=> 0,
                'course_language' => 0,
                'user_id' => 1, 'course_aproved' => 1, 
                'main_id' => 8,
            ],
            [
                'course_url' => "http://www.phptherightway.com/?ref=${domain}",
                'course_name' => "PHP The Right Way",
                'course_type' => 0,
                'course_price_type'=> 0,
                'course_language' => 0,
                'user_id' => 1, 'course_aproved' => 1, 
                'main_id' => 8,
            ],
            [
                'course_url' => "http://www.nusphere.com/php/php_tutorial.htm?ref=${domain}",
                'course_name' => "PHP Tutorial",
                'course_type' => 0,
                'course_price_type'=> 0,
                'course_language' => 0,
                'user_id' => 1, 'course_aproved' => 1, 
                'main_id' => 8,
            ],
            [
                'course_url' => "https://www.youtube.com/playlist?list=PLillGF-Rfqbap2IB6ZS4BBBcYPagAjpjn&ref=${domain}",
                'course_name' => "PHP Front To Back",
                'course_type' => 0,
                'course_price_type'=> 0,
                'course_language' => 0,
                'user_id' => 1, 'course_aproved' => 1, 
                'main_id' => 8,
            ],
            [
                'course_url' => "https://click.linksynergy.com/deeplink?id=jU79Zysihs4&mid=40328&murl=https://www.coursera.org/specializations/python",
                'course_name' => "Python for Everybody Specialization",
                'course_type' => 0,
                'course_price_type'=> 0,
                'course_language' => 0,
                'user_id' => 1, 'course_aproved' => 1, 
                'main_id' => 9,
            ],
            [
                'course_url' => "https://linkedin-learning.pxf.io/932NY",
                'course_name' => "Learning Python with PyCharm",
                'course_type' => 0,
                'course_price_type'=> 0,
                'course_language' => 0,
                'user_id' => 1, 'course_aproved' => 1, 
                'main_id' => 9,
            ],
            [
                'course_url' => "https://click.linksynergy.com/deeplink?id=jU79Zysihs4&mid=39197&murl=https://www.udemy.com/course/complete-python-bootcamp/",
                'course_name' => "Complete Python Bootcamp",
                'course_type' => 0,
                'course_price_type'=> 0,
                'course_language' => 0,
                'user_id' => 1, 'course_aproved' => 1, 
                'main_id' => 9,
            ],
            [
                'course_url' => "https://geni.us/XNd0BY?ref=${domain}",
                'course_name' => "Learn Python the Hard Way",
                'course_type' => 0,
                'course_price_type'=> 0,
                'course_language' => 0,
                'user_id' => 1, 'course_aproved' => 1, 
                'main_id' => 9,
            ],
            [
                'course_url' => "https://click.linksynergy.com/deeplink?id=jU79Zysihs4&mid=39197&murl=https://www.udemy.com/react-the-complete-guide-incl-redux",
                'course_name' => "React - The Complete Guide (incl Hooks, React Router, Redux)",
                'course_type' => 0,
                'course_price_type'=> 0,
                'course_language' => 0,
                'user_id' => 1, 'course_aproved' => 1, 
                'main_id' => 10,
            ],
            [
                'course_url' => "https://www.youtube.com/watch?v=Ke90Tje7VS0&ref=${domain}",
                'course_name' => "React Crash Course 2018 - React Tutorial with Examples",
                'course_type' => 0,
                'course_price_type'=> 0,
                'course_language' => 0,
                'user_id' => 1, 'course_aproved' => 1, 
                'main_id' => 10,
            ],
            [
                'course_url' => "https://click.linksynergy.com/deeplink?id=jU79Zysihs4&mid=39197&murl=https://www.udemy.com/react-2nd-edition/?ref=${domain}",
                'course_name' => "The Complete React Web Developer Course (with Redux)",
                'course_type' => 0,
                'course_price_type'=> 0,
                'course_language' => 0,
                'user_id' => 1, 'course_aproved' => 1, 
                'main_id' => 10,
            ],
            [
                'course_url' => "https://click.linksynergy.com/deeplink?id=jU79Zysihs4&mid=39197&murl=https://www.udemy.com/modern-react-bootcamp/",
                'course_name' => "The Modern React Bootcamp",
                'course_type' => 0,
                'course_price_type'=> 0,
                'course_language' => 0,
                'user_id' => 1, 'course_aproved' => 1, 
                'main_id' => 10,
            ],
            [
                'course_url' => "https://click.linksynergy.com/deeplink?id=jU79Zysihs4&mid=39197&murl=https://www.udemy.com/artificial-intelligence-az/",
                'course_name' => "Artificial Intelligence A-Z: Learn How To Build An AI",
                'course_type' => 0,
                'course_price_type'=> 0,
                'course_language' => 0,
                'user_id' => 1, 'course_aproved' => 1, 
                'main_id' => 11,
            ],
            [
                'course_url' => "https://www.udacity.com/course/intro-to-artificial-intelligence--cs271?ref=${domain}",
                'course_name' => "Intro to Artificial Intelligence - Udacity",
                'course_type' => 0,
                'course_price_type'=> 0,
                'course_language' => 0,
                'user_id' => 1, 'course_aproved' => 1, 
                'main_id' => 11,
            ],
            [
                'course_url' => "https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-034-artificial-intelligence-fall-2010/lecture-videos/?ref=${domain}",
                'course_name' => "MIT Open Courseware - Artificial Intelligence",
                'course_type' => 0,
                'course_price_type'=> 0,
                'course_language' => 0,
                'user_id' => 1, 'course_aproved' => 1, 
                'main_id' => 11,
            ],
            [
                'course_url' => "https://course.elementsofai.com?ref=${domain}",
                'course_name' => "Elements of AI",
                'course_type' => 1,
                'course_price_type'=> 0,
                'course_language' => 0,
                'user_id' => 1, 'course_aproved' => 1, 
                'main_id' => 11,
            ],
            [
                'course_url' => "https://click.linksynergy.com/deeplink?id=jU79Zysihs4&mid=40328&murl=https://www.coursera.org/professional-certificates/ibm-data-science",
                'course_name' => "IBM Data Science Professional Certificate",
                'course_type' => 0,
                'course_price_type'=> 0,
                'course_language' => 0,
                'user_id' => 1, 'course_aproved' => 1, 
                'main_id' => 12,
            ],
            [
                'course_url' => "https://www.youtube.com/watch?v=tokjknQWJ4o&ref=${domain}",
                'course_name' => "Tableau Training for Beginners Session -1",
                'course_type' => 0,
                'course_price_type'=> 0,
                'course_language' => 0,
                'user_id' => 1, 'course_aproved' => 1, 
                'main_id' => 12,
            ],
            [
                'course_url' => "http://cs109.github.io/2015/?ref=${domain}",
                'course_name' => "CS109 Data Science",
                'course_type' => 0,
                'course_price_type'=> 0,
                'course_language' => 0,
                'user_id' => 1, 'course_aproved' => 1, 
                'main_id' => 12,
            ],
            [
                'course_url' => "https://click.linksynergy.com/deeplink?id=jU79Zysihs4&mid=39197&murl=https://www.udemy.com/datascience/",
                'course_name' => "Data Science A-Z",
                'course_type' => 0,
                'course_price_type'=> 0,
                'course_language' => 0,
                'user_id' => 1, 'course_aproved' => 1, 
                'main_id' => 12,
            ],
            [
                'course_url' => "https://www.rainbowtraininginstitute.com/devops-training/devops-online-training?ref=hackr.io",
                'course_name' => "Devops Training | Rainbow Training",
                'course_type' => 0,
                'course_price_type'=> 0,
                'course_language' => 0,
                'user_id' => 1, 'course_aproved' => 1, 
                'main_id' => 13,
            ],
            [
                'course_url' => "https://www.rainbowtraininginstitute.com/amazon-web-services-aws-training/aws-online-training?ref=${domain}",
                'course_name' => "AWS Training | Rainbow TrainingTraining",
                'course_type' => 0,
                'course_price_type'=> 0,
                'course_language' => 0,
                'user_id' => 1, 'course_aproved' => 1, 
                'main_id' => 13,
            ],
            [
                'course_url' => "https://click.linksynergy.com/deeplink?id=jU79Zysihs4&mid=39197&murl=https://www.udemy.com/docker-and-kubernetes-the-complete-guide",
                'course_name' => "Docker and Kubernetes: The Complete Guide",
                'course_type' => 0,
                'course_price_type'=> 0,
                'course_language' => 0,
                'user_id' => 1, 'course_aproved' => 1, 
                'main_id' => 14,
            ],
            [
                'course_url' => "https://serversforhackers.com/getting-started-with-docker/?ref=${domain}",
                'course_name' => "Getting Started with Docker",
                'course_type' => 0,
                'course_price_type'=> 0,
                'course_language' => 0,
                'user_id' => 1, 'course_aproved' => 1, 
                'main_id' => 14,
            ],
            [
                'course_url' => "https://click.linksynergy.com/deeplink?id=jU79Zysihs4&mid=39197&murl=https://www.udemy.com/linux-command-line-volume1/",
                'course_name' => "Linux Command Line Basics",
                'course_type' => 0,
                'course_price_type'=> 0,
                'course_language' => 0,
                'user_id' => 1, 'course_aproved' => 1, 
                'main_id' => 15,
            ],
            [
                'course_url' => "http://www.awin1.com/cread.php?awinmid=6798&awinaffid=428263&p=https://www.edx.org/course/introduction-linux-linuxfoundationx-lfs101x-1?ref=${domain}",
                'course_name' => "Introduction to Linux",
                'course_type' => 0,
                'course_price_type'=> 0,
                'course_language' => 0,
                'user_id' => 1, 'course_aproved' => 1, 
                'main_id' => 15,
            ],
        ];


        foreach($courses as $course) {
            Course::insert($course);
        }
    }
}       
